### ISSUE TITLE
REQUEST: New/alter membership - Víctor Mayoral as "Member"

### ISSUE THREAD

**Issue by vmayoral** [ros-security/community#2]
### Request
This tickets aims to request ~~"Approver"~~ "Member" (**edited**, see below) privileges in the Security WG's infrastructure.

### Requirements
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more projects under the ROS 2 Security Working Group
  - various ROS and ROS 2 packages

### Sponsors (if applicable)
- [Alias Robotics](aliasrobotics.com/)

### List of contributions to ROS 2 Security Working Group
- PRs reviewed / authored
  - https://github.com/ros2/rcl/pull/509
  - https://github.com/ros2/rcl/pull/537
  - https://github.com/AcutronicRobotics/moveit2/pull/113
  - https://github.com/ros2/rcl/pull/468
  - and more (see https://github.com/vmayoral/) for more public contributions
  
- Issues triaged
  - https://github.com/aliasrobotics/RVD/issues/333
  - https://github.com/aliasrobotics/RVD/issues/88      
  - https://github.com/aliasrobotics/RVD/issues/87
  - https://github.com/aliasrobotics/RVD/issues/167
  - https://github.com/aliasrobotics/RVD/issues/918
    - [more for ROS](https://github.com/aliasrobotics/RVD/issues?utf8=%E2%9C%93&q=is%3Aissue+-label%3Atriage+label%3A%22robot+component%3A+ROS%22+-label%3Ainvalid+is%3Aall++-label%3Arobust+)
    - [more for ROS 2](https://github.com/aliasrobotics/RVD/issues?q=is%3Aissue+-label%3Atriage+label%3A%22robot+component%3A+ROS2%22+-label%3Ainvalid+-label%3Aduplicate+is%3Aclosed)

- Other relevant project involvement
  - Security-related:
     - https://github.com/aliasrobotics/RVD
     - https://github.com/aliasrobotics/aztarna
     - https://github.com/aliasrobotics/ros_volatility
     - https://github.com/aliasrobotics/RVSS
     - https://github.com/aliasrobotics/RCTF
     - https://github.com/aliasrobotics/MARA_threat_model
     - https://github.com/aliasrobotics/RSF
  - Non-security by ROS (Quite a few, frankly. Listing some)
     - https://github.com/ros-controls/ros_control
     - https://github.com/ros2/design
     - https://github.com/ros-planning/moveit2
     - ...

**Comment by kyrofa** [comment]
Thanks for the application! I'm sorry it hasn't gotten a comment yet. Here's why:

>  - [x] I am actively contributing to 1 or more projects under the ROS 2 Security Working Group
>    - various ROS and ROS 2 packages

"Various ROS and ROS 2 packages" aren't under the ROS 2 security working group. In fact... none really are. We're working on that, at which time we'll have the proper context for membership.

**Comment by kyrofa** [comment]
Once again, I apologize for the delay. The Security Working Group is an open group. Anyone can attend our meetings, the Matrix room, etc. and participate in our discussions, without being a member of this particular GitHub org. This org was created in order for the WG to maintain projects as a team, which involves splitting responsibilities up across that team. That's why applications need to be evaluated in light of the projects we maintain. However, we only just started maintaining one, the SROS2 utilities, thus the delay.

Your general involvement in the ROS community is laudable, thank you for that! However, given that what we're talking about here is maintenance of the SROS2 utilities, a project with which you haven't been very involved, I think the role of Approver is not appropriate at this time. Member is probably the best place to start if you're willing to take on triaging responsibility.

**Comment by vmayoral** [comment]
Thanks @kyrofa. Seems fair, I really do not have direct contributions to SROS2 for the moment but hopefully that'll change :).

I'd be happy to take on triaging SROS2 flaws and participate as a Member.

**Comment by mikaelarguedas** [comment]
+1 for the application as a member and the attached rationale, reiterating that all roles are dynamic and can be revisited based on contributions to projects in the WG as well as the evolution of the list of projects in the WG.

Looking forward to working more closely with you on this @vmayoral !

**Comment by kyrofa** [comment]
Done. Thank you! @vmayoral, if at any point you feel unable to satisfy the duties of Member, please let us know.
